spring:
  datasource:
    url: jdbc:mysql://ccv3.infra.kurt:3306/test
    username: app
    password: Fastone1!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update