spring:
  datasource:
    url: jdbc:postgresql://52.82.77.247:5432/kurt-test-new
    driver-class-name: org.postgresql.Driver
    username: sa
    password: boKYLXIERWnzB0gX
  jpa:
    hibernate:
      ddl-auto: create